### ISSUE TITLE
WebRTC SFU support Pion?

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc#1047]
Is there some update on this: https://www.jsxc.org/blog/2021/03/12/We-get-founded.html already?

Maybe a good backend for a WebRTC SFU would be this: https://github.com/pion/ion-sfu

There is also some talk about direct browser-screensharing to streaming service via Pion. Maybe that would be interesting to directly stream to a one-to-many service from JSXC? Edit: or a video recording end-point like this: https://github.com/node-webrtc/node-webrtc-examples/tree/master/examples/record-audio-video-stream

**Comment by sualko** [comment]
Thanks for your request. It's nice to see that someone is keeping an eye on the project.

Since the founding period is ending this month there will be a "final" report probably next week. The p2p video plugin is already in the repository (but it needs some more testing) and the SFU will be published probably this week. Ion looks really cool and I'm sad that I was not aware of it a few month ago (even if the documentation seams to be pretty poor). Currently I use [Kurento](https://kurento.org/) which works quite nice, but doesn't allow to add multiple streams in one connection. So Ion could maybe have a better performance. For the signaling I'm using a combination of muc messages and custom websocket server, because I do not have the skills / time to everything as XMPP server module.

I will keep this issue open until the blog post was published.

**Comment by poVoq** [comment]
Cool, looking forward to it.

So multi-party jingle calls via p2p WebRTC already work?

**Comment by poVoq** [comment]
https://www.jsxc.org/blog/2021/08/31/A-group-call-proposal.html

Thanks for the update :)
