### ISSUE TITLE
notification icon for minimized chat window

### ISSUE THREAD

**Issue by v1r0x** [jsxc/jsxc#146]
I have the problem, that if I get a new message (and didn't see it) and switch back to the chat tab, a little notification on the minimized chat tab would be great, to recognize the corresponding tab. Something like this (the "2" on the yellow background is what I miss ;) ):
![jsxc-mini-noti](https://cloud.githubusercontent.com/assets/9248714/7069224/cbd0dbf4-ded7-11e4-8611-0e9fd794286e.png)

**Comment by sualko** [comment]
Do you miss the entire circle or only the number? Because in the current version you have two markers for unread messages:

![unread2](https://cloud.githubusercontent.com/assets/2974196/7070099/1280629a-dedd-11e4-902f-afbbb56c41ed.PNG)
![unread](https://cloud.githubusercontent.com/assets/2974196/7070102/16a0b5dc-dedd-11e4-86e4-877d72f9494c.PNG)

**Comment by v1r0x** [comment]
Not it works....weird. Don't know why it didn't work earlier.
But: A number would be cool :)

**Comment by sualko** [comment]
I put it on my list.
