### ISSUE TITLE
Bookmarks (XEP-0048)

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#165]
Implement [Bookmarks (XEP-0048)](https://xmpp.org/extensions/xep-0048.html) to store group chats.

**Comment by v1r0x** [comment]
offtopic: First of all, thanks again for your effort! Really great to have muc integrated.

ontopic: I joined a room with my own user and a test user. With the test user I didn't left the room, but closed the browser and in my other browser I got the notification that this user left the room.
I think this is related to this issue? If not I'll open an issue, otherwise I'm happy that this is already planned and exited to have/test it.

**Comment by sualko** [comment]
It is not related and I think also that this is no issue at all, because if you go offline you also leave all joined rooms.

**Comment by v1r0x** [comment]
This is kind of related.
Currently you have to re-join a room after logout (which is the right behavior in XEP-0045), with XEP-0048 you can re-join automatically. The problem on my side was, that the rooms were not persistant and were destroyed after the last user left.
And I thought MUC means the same as it is in (e.g.) facebook, but XMPP doesn't support this (only as a combination of XEP-0045 and XEP-0048).
Beside that: works great! :)

**Comment by shaggybb** [comment]
Due to my lack of knowledge about XMPP extensions, currently I'm using the roster to store the rooms that I want to join automatically. Personally I think XEP-0048 is a fantastic solution and it avoids abnormal responses like, in my case, malformed-jid and reduces complexity.

I think would be nice to use https://github.com/strophe/strophejs-plugins/tree/master/bookmarks
