### ISSUE TITLE
Fix JS to comply with LibreJS

### ISSUE THREAD

**Issue by pizzamaker** [jsxc/jsxc#184]
The following script is either unfree/untagged/unrecognized by the LibreJS extension:

 NONTRIVIAL: an open method similar to xhr.open is used
 https://diasporabr.com.br/assets/jsxc-e660beffa5fa259ea8f528e10ad756d7.js

For more info, see here: https://github.com/diaspora/diaspora/issues/6103#issuecomment-111828117

**Comment by sualko** [comment]
I haven't ever heard of librejs and it seams to work not very well with minified javascript. Additional it has the following policies, which we are violating:

- calling methods with the square bracket notation
- it makes an AJAX request

Sorry, but this is required for jsxc. 

I could add the <code>@source</code> attribute to all files, but I will not add <code>@licstart/@licend</code> to my files, because this makes no sense in my eyes. 

Please add a exception for jsxc to librejs.
