### ISSUE TITLE
no login possible when using ojsxc 2.1.0 with Safari

### ISSUE THREAD

**Issue by DanScharon** [jsxc/jsxc#204]
With ojsxc 2.1.0 it is not possible to log in using Safari. The login box is inoperable and the alternate offer to login without chat is not loaded.

Using other browsers works and using Safari with ojsxc 2.0.1 too.

**Comment by efelon** [comment]
Login also doesn't work anymore for:
- IExplorer (11.0.9600.17633)  Login button without function
- Chrome (40.0.2214.91) Login starts, but gets stuck in chat login

Firefox not affected.

**Comment by sualko** [comment]
For Safari I get the following error:

```
ReferenceError: Can't find variable: RTCPeerConnection. jsxc.dep.js:25452
```

I guess some similar error occurs in ie and chrome < 40. Please check your javascript console and look for errors.

This error should be fixed with webrtc/adapter#63. I will update the required libraries asap.

**Comment by sualko** [comment]
Should work now in safari and ie. I can not test chrome 40, because I have no such old version. Please close this issue if the fix satisfies you.

**Comment by anonimal** [comment]
I'm also having this problem with Firefox 31.8.0. Has anyone tested this against Firefox?

Web console also produces:

<code>Content Security Policy: The page's settings blocked the loading of a resource: An attempt to execute inline scripts has been blocked</code>

but I imagine that is because I'm not using a proxy and because of OC 8.1 #201.

Note: ojsxc v2.0.1 works seamlessly. Nothing has changed in my configuration between v2.0.1 and v2.1.0

**Comment by sualko** [comment]
@anonimal Does your login box response? If yes, please open a new issue. If no, please post the file name and line number which produces this error message. With oc 8.1 you have to use a proxy, so jsxc v2.0.1 and oc 8.1 should also not work without a proxy.

**Comment by efelon** [comment]
Can you please tell me how to test this fix with owncloud?

**Comment by sualko** [comment]
The easiest way is to search for the lines from https://github.com/webrtc/adapter/pull/63/files and replace them accordantly in jsxc.dep.js.

The harder way is to follow our [developer notes](https://github.com/jsxc/jsxc/wiki/Developer-notes).

I will wait until Monday to release a bug fix release, because maybe other bugs will show up.

**Comment by efelon** [comment]
Thanks, for the hint. Didn't know it is about jsxc.dep.js.
I found and changed a line according to the line 387 from you fix, which got the login working. 
However, I wasn't able to find another place as in your fix line 401.

Maybe that's why in the about dialog I get:

> Libraries: < $ dep.libraries $>

**Comment by anonimal** [comment]
@sualko No, the login button does not function and the <i>Log in without chat</i> text does not appear.

#### Solution (Firefox)
I'm also receiving a similar error: <code>ReferenceError: RTCPeerConnection is not defined jsxc.dep.js:24577</code> in Firefox but now that I've applied the above Safari fix to jsxc.dep.js, this v2.1.0 issue is now resolved - at least with Firefox. Thank you!

@sualko I'm still not using a proxy but everything seems to work well. Firefox is still complaining with the CSP message though I'm able to use OC and ojsxc just fine. Everything is all on the same domain though, so I imagine that's why it works?

**Comment by sualko** [comment]
@anonimal Normally it should also block requests to different ports, but I will not complain ;-).

@efelon Please open a new issue for your typeerror, enable [jsxc debugging](https://github.com/jsxc/jsxc/wiki/Owncloud-Debugging) and post a screenshot of your js console.

**Comment by anonimal** [comment]
@sualko why was this not included in v2.1.1 to present v2.1.4?
```git```
diff --git a/build/lib/jsxc.dep.js b/build/lib/jsxc.dep.js
index db2c219..e07db66 100644
--- a/build/lib/jsxc.dep.js
+++ b/build/lib/jsxc.dep.js
@@ -19078,7 +19078,7 @@ if (typeof module !== 'undefined') {
     RTCPeerConnection = window.RTCPeerConnection;
   }
   module.exports = {
-    RTCPeerConnection: RTCPeerConnection,
+    RTCPeerConnection: window.RTCPeerConnection,
     getUserMedia: getUserMedia,
     attachMediaStream: attachMediaStream,
     reattachMediaStream: reattachMediaStream,
```

**Comment by sualko** [comment]
Isn't it? 

My jsxc.dep.js looks like this:

```
if (typeof module !== 'undefined') {
  var RTCPeerConnection;
  if (typeof window !== 'undefined') {
    RTCPeerConnection = window.RTCPeerConnection;
  }
  module.exports = {
    RTCPeerConnection: RTCPeerConnection,
    getUserMedia: getUserMedia,
    attachMediaStream: attachMediaStream,
    reattachMediaStream: reattachMediaStream,
    webrtcDetectedBrowser: webrtcDetectedBrowser,
    webrtcDetectedVersion: webrtcDetectedVersion,
    webrtcMinimumVersion: webrtcMinimumVersion,
    webrtcTesting: webrtcTesting
    //requestUserMedia: not exposed on purpose.
    //trace: not exposed on purpose.
  };
} else if ((typeof require === 'function') && (typeof define === 'function')) {
  // Expose objects and functions when RequireJS is doing the loading.
  define([], function() {
    return {
      RTCPeerConnection: window.RTCPeerConnection,
      getUserMedia: getUserMedia,
      attachMediaStream: attachMediaStream,
      reattachMediaStream: reattachMediaStream,
      webrtcDetectedBrowser: webrtcDetectedBrowser,
      webrtcDetectedVersion: webrtcDetectedVersion,
      webrtcMinimumVersion: webrtcMinimumVersion,
      webrtcTesting: webrtcTesting
      //requestUserMedia: not exposed on purpose.
      //trace: not exposed on purpose.
    };
  });
}
```

I think this should be fine. It also works with Safari and v2.1.4.

**Comment by anonimal** [comment]
I see now, I didn't read ahead. I was :sleeping: when combing through commits.
Thanks for clarifying.

**Comment by sualko** [comment]
The most important thing is that it works now for you.
