### ISSUE TITLE
If BOSH server is down, can't login

### ISSUE THREAD

**Issue by Ezerbeth** [jsxc/jsxc#207]
All I get in a "please wait while logging in" message, and the Apache logs say:

[Sun Aug 09 07:28:19 2015] [error] [client xx.xx.xx.xx] File does not exist: /usr/local/www/owncloud/bosh.server.here, referer: https://my.owncloud.url.com

And nothing ever happens. I had to move the application outside the apps/ directory to be able to access OC again.

**Comment by sualko** [comment]
I can confirm your issue and it seems to me, like there is a bug in the xmpp library. I will try to fix it upstream, but this can take some time.

In my little test, I was able to login to owncloud via "Login without chat". Was this also not working for you?

**Comment by mdik** [comment]
Kind of related to this bug is what we discussed yesterday evening: Making the "Login without chat" button look like a button and disabling the chat for the admin user alltogether, although I guess more opinions on the latter are needed to make a good decision: Do people use the administrative account as their normal account or do they have separate admin and user accounts?
