### ISSUE TITLE
SMF integration

### ISSUE THREAD

**Issue by souperk** [jsxc/jsxc#209]
Hello, I am working on the SMF (http://simplemachines.org). Since, I am not experienced with javascript I will need some help, I hope you can put up with me.

Let's start! 

1)How can I register an account to the xmpp server using jsxc? I searched jsxc.js but I couldn't find anything related. Is this functionality not implemented? 

If it not implements maybe we can use this https://github.com/metajack/strophejs-plugins/tree/master/register .

2) Is there a way to connect using SHA1 hashed password? SMF for security reason stores passwords in the form of SHA1 hashed value. For now, in order to overcome this I registered my users using the SHA1 hash, however this means that the user can't login to the xmpp server with any other client.

I think it is possible in the xmpp protocol. Anyway, any hints for this will be appreciated.

**Comment by sualko** [comment]
1) Check #178

2) Our used xmpp library supports SASL-SCRAM which can uses SHA-1, but this does not help, because it is salted. You do not need to login with SHA1 hashed passwords at all, because only your xmpp server has to verify that the password is valid and this can be done by doing the hashing and comparing on the server side. e.g. Client sends plaintext password to server; server calculates sha1; server compares sha1 value with stored value.

We would be happy if we could publish your finished integration on our website. Do you have any link to that and is this generally ok for you?

**Comment by sualko** [comment]
If you have any updates or problems on this project, please let me know.
