### ISSUE TITLE
Multiline message

### ISSUE THREAD

**Issue by thfree** [jsxc/jsxc#300]
Can not send a multiline message.
OC 8.2
JSXC 3.0.0
##

**Comment by sualko** [comment]
see #278

**Comment by ChristianTacke** [comment]
A bit related (please let me know, if I should file a distinct enhancement request):

When typing a longer (possibly multi line) message, it would be very helpful to use more space for the input area. Even a simple config option to have two or three input lines instead of one would be helpful. Auto growing would be cool, of course.

**Comment by sualko** [comment]
No need for a second ticket. I understand your issue and I think it should be not too complicated to implement.

**Comment by thfree** [comment]
Thank you, now I can use again.
