### ISSUE TITLE
Using jsxc with own online roster

### ISSUE THREAD

**Issue by Cronetos** [jsxc/jsxc#314]
I would like to implement jsxc into a project of mine. We already have a user online list and I would like to use that instead of the online roster of jsxc. Is there a way to disable the online list and open a chat box via a link? I hope it's okay to ask here for support. I have not been able to figure it out myself by reading through the jsxc.js file. Any help is greatly appreciated. Thanks in advance.

**Comment by Cronetos** [comment]
Okay, I found a way to do it.
I uncommented line 3871. 
//$(jsxc.options.rosterAppend + ':first').append($(jsxc.gui.template.get('roster')));
Maybe this helps somebody as well.
Chats can be open by using jsxc.gui.window.open(bid);
Is there a better way to do it?

**Comment by sualko** [comment]
> I uncommented line 3871. 

This feels like a bad idea, because I am afraid of side effects. You could also set <code>display:none;</code> for <code>#jsxc_roster</code>.

> Is there a better way to do it?

You could use links with urls like <code>xmpp:romeo@montague.net?message</code>, because we are supporting [URI Scheme Query (XEP-0147)](http://xmpp.org/extensions/xep-0147.html). You probably have to call <code>jsxc.gui.detectUriScheme(container)</code> to detect them.

If you have no further questions, please close this issue :wink:.

**Comment by Cronetos** [comment]
Thanks for the quick and very helpful reply. Excellent library
