### ISSUE TITLE
Multiple ldap authentication

### ISSUE THREAD

**Issue by reeyon** [jsxc/jsxc#323]
Hi, can we have multiple ldap authentication at the same time? 
In the owncloud setting, we only can specify single XMPP Domain, can we define more than one?

Our environment has 2 different domains users, we have successfully created 2 ldap authentication for 2 domains and tested working fine.

So i log on owncloud with second domain account, it doest passed the @domain.com to external ejabberd, so chat doent work.

One thing to clarify with you, what is the function of the script of auth_ejabberd_oc.php and auth_oc_user.php? Should i use these scripts as external command while we have external ejabberd.
What is XMPP resource? What should i put in the setting? Sorry for many questions, we are new to ejabberd.

Thank you.
##

**Comment by sualko** [comment]
> can we have multiple ldap authentication at the same time? 

You could force your users to enter there full jabber id (aka email address). Otherwise you could also modify [getSettings.php](https://github.com/owncloud/jsxc.chat/blob/master/ajax/getSettings.php#L43) to respond with the correct xmpp domain.

> what is the function of the script of auth_ejabberd_oc.php and auth_oc_user.php?

Both files are used to authenticate ejabberd against owncloud, but while you are using ldap this is useless for you.

> What is XMPP resource?

See http://wiki.xmpp.org/web/Jabber_Resources

> Thank you.

No problem.

**Comment by reeyon** [comment]
Hi, sorry for late reply. Been busy lately.

> You could force your users to enter there full jabber id (aka email address). Otherwise you could also modify getSettings.php to respond with the correct xmpp domain.

ownCloud does not allowed me to input full jab id when I try to login. It shows "wrong password". It's only allow me to login without the domain name.

How would I do that? Thank you.

**Comment by MarcelWaldvogel** [comment]
@reeyon Can you try owncloud/jsxc.chat#26?
