### ISSUE TITLE
[Del] key in chat deletes email when integrated in ownCloud

### ISSUE THREAD

**Issue by pmetras** [jsxc/jsxc#360]
Hello,

When jsxc chat is integrated in ownCloud, using the [Delete] key to delete typed characters deletes also emails, when the chat pane is on the Mail app. This is quite frustrating...
Possibly other characters have similar functions both in jsxc and ownCloud apps. The chat fields should capture entered characters and not cascade to the other apps or the browser.
## Bug happens with ownCloud 8.2.7 and jsxc 3.0.0 with Vivaldi browser 1.2.490.43.

Pierre Métras
##

**Comment by sualko** [comment]
The problem is, that there are 3 different events for an key stroke and I would have to catch them all. Meanwhile it is more a task of the mail app to check if this key stroke is intended for them or not, like they actually do it in [appview.js#L126](https://github.com/owncloudarchive/mail/blob/master/js/views/appview.js#L121). I tested this snippet (without the mail app) and it works quit well.

Maybe the input lost focus before you key DEL?
