### ISSUE TITLE
enable only for certain groups within Own/Nextcloud

### ISSUE THREAD

**Issue by joergmschulz** [jsxc/jsxc#379]
While some (most) OC / NC apps have the checkbox 'enable only for group...', ojsxc doesn't.
How is it possible to restrict access to chat to a group of users?

**Comment by sualko** [comment]
Such a checkbox is currently not possible, because jsxc have to be loaded before the user is logged in. You can get the same result if you check the group affiliation in [getSettings.php](https://github.com/owncloud/jsxc.chat/blob/master/ajax/getSettings.php) and set ``$data ['loginForm'] ['enable']  = false;``. Additionally you have to check that in [app.php](https://github.com/owncloud/jsxc.chat/blob/master/appinfo/app.php) and disable all javascripts.
