### ISSUE TITLE
How to auto join in to persistent chat room after login

### ISSUE THREAD

**Issue by sikkandar** [jsxc/jsxc#419]
Please tell me is there any way to auto join the chat rooms after login. while creating room i have marked bookmark and auto join checkbox. After logout and relogin the rooms are visible in roster window. But the rooms are not visible after clearing the browser history. 
I manually added the group chat bookmarks in Openfire Xmpp server and login with jsxc then it will show the rooms in roster window permanently even i cleared the browser history also.
Please tell me how to add the room bookmarks in to openfire group chat bookmark or is there any other way to achieve this.

**Comment by mmoqui** [comment]
I think this problem comes from OpenFire. After a successful login, JSXC fetch bookmarked buddies and group chats. But before fetching remote bookmarks, JSXC checks the XMPP server supports the group chat bookmarking functionality. If the server doesn't support it, then JSXC works only with the local bookmarks. 
Before passing from OpenFire to Ejabberd, we have discovered the group chat bookmarking functionality is buggy in OpenFire as it responds to no to JSXC request for its support for group chat bookmarking.

**Comment by sikkandar** [comment]
But my open fire xmpp server has the bookmarks feature. i thing it is not getting the bookmarks from my open fire server.Thanks for your valuable response. Do u have any idea how to get the bookmarks form openfire server.
![capture](https://cloud.githubusercontent.com/assets/23522801/21073684/afd6775e-bf0b-11e6-9f61-f6f7dff0f47f.PNG)

**Comment by mmoqui** [comment]
yes, in Javascript:
```
$(document).on('ready.roster.jsxc', function() {
   jsxc.debug('Force to load group chats from OpenFire');
   jsxc.xmpp.bookmarks.loadFromRemote();
});
```

**Comment by sualko** [comment]
@mmoqui is totally right. JSXC tries to determine bookmark (PUBSUB) via CAPS and if this check fails, it fail back to local storage. You can test bookmark support via `jsxc.xmpp.bookmarks.remote()`.

**Comment by sikkandar** [comment]
jsxc.xmpp.bookmarks.remote() doesn't work. i can't fetch any bookmarks from open fire.

**Comment by sualko** [comment]
`remote()` should only return true or false which means, support, or no support. If it returns false and you are sure, that your server supports pubsub, you can use mmoquis workaround.
