### ISSUE TITLE
external auth scripts missing in latest versions

### ISSUE THREAD

**Issue by rossdraper** [jsxc/jsxc#446]
Wiki entry here https://github.com/jsxc/jsxc/wiki/Install-ejabberd-(owncloud)-%7C-Ubuntu-12.04
references to external auth scripts for integration with nextcloud/owncloud.

Neither of these scripts seem to exist anymore - how is authentication to owncloud/nextcloud authentication now handled?

Thanks

Ross

**Comment by sualko** [comment]
see jsxc/jsxc.nextcloud#2

**Comment by sualko** [comment]
We decided that we will rewrite the authentication script from scratch, because we think there is a real need for this (as seen from all those requests). You will find the updated script in [jsxc/ejabberd-cloud-auth](https://github.com/jsxc/ejabberd-cloud-auth). To get an notification subscribe to this new repo.
