### ISSUE TITLE
i dont know where to find auth_ejabberd_oc.php and auth_ejabberd_oc.php

### ISSUE THREAD

**Issue by bigbigQI** [jsxc/jsxc#451]

**Comment by MarcelWaldvogel** [comment]
See jsxc/jsxc.nextcloud#2

**Comment by sualko** [comment]
We decided that we will rewrite the authentication script from scratch, because we think there is a real need for this (as seen from all those requests). You will find the updated script in [jsxc/ejabberd-cloud-auth](https://github.com/jsxc/ejabberd-cloud-auth). To get an notification subscribe to this new repo.
