### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by sualko** [jsxc/jsxc#463]
It is time to do some refactoring to get a better structure and improve extensibility. In this issue I want to collect ideas and wishes from you to get the best from this huge step (which will result in JSXC v4.0). It will probably last a couple of month and every line of code will be touched. My goals for this project are the following in descending importance:

1) Make the code testable (fix #191 )
2) Smaller files
3) Improve tab communication (fix #328)
4) Improve security (XSS, ...)
5) Easy & durable integration
6) Easy extensibility

To reach the goals I propose the following changes:

- Use [TypeScript](https://www.typescriptlang.org) with modules
- Use more objects (stricter encapsulation and smaller functions)
- Use promises instead of callbacks
- Create new tab communication
- Create public API with versions (e.g. `jsxc.api.v1.start`)
- Create message pipes for incoming and outgoing messages

Additionally I would like to think about the following points:

- Is Grunt still state of the art? I feel comfortable with it, but maybe there is a better solution which fits our needs. (Gulp, webpack,...)
- The css naming is quiet uncommon and inconsistent. I am inclined to something like `jsxc-roster-toggle` instead of `jsxc_rosterToggle`.

I would love to hear your thoughts @LEDfan @MarcelWaldvogel @Zauberstuhl @johangm90 @dimaursu @nitmir @ChristianTacke @dteleguin @skyfox675

**Comment by johangm90** [comment]
I have never used Grunt, I started using Gulp following several recommendations and in my opinion it is quite good

**Comment by mmoqui** [comment]
In the way of improving the code: a  better decoupling between the UI and the engine by using, for example, the events.

**Comment by sualko** [comment]
Thank you for the feedback. In the meanwhile I started to experiment with typescript, handlebars, karma, chai, mocha and sinon. It's looking promising and I will publish first results of the rewrite, if I feel that I found a working setup and style.

**Comment by krazyjakee** [comment]
Hey all! Just going to thought dump...

- I would propose babel as a preprocessor instead of typescript as ES6 has modules and is a lot easier to setup and use. It's also much more accessible for the majority of potential javascript contributors. When the time comes, you can just remove babel and the code won't have to be refactored. Sorry if I've triggered anyone, it's just that after seeing so many non-standard pre-compilers over the years, it hurts me to see them forced onto any would-be contributors who can't afford the time to hit that learning curve.
- Webpack is what is currently "state-of-the-art" but grunt and gulp are still good. If you are comfortable with grunt and it moves the project forward, I would just go with that. I personally prefer gulp to grunt, just because I feel I have more power in a simpler configuration.
- I think @mmoqui suggestion is really interesting. It would make unit testing much easier if the engine has no care or reference to the UI.

**Comment by sualko** [comment]
I also looked into babel, but I liked the concept of types and with Microsoft and Google (angular) there should be enough support so that this will be no second coffeescript :wink:. Btw. Typescript 2 uses also ES6 modules.

**Comment by krazyjakee** [comment]
I won't argue, but I will say that I was VERY wrong about coffeescript and that crap can burn in hell.

**Comment by mmoqui** [comment]
Hum... I don't have any advice about TypeScript. My only advice is just to find the better tradeoff between complexity and added value. Complexity is added by the written code but also more often by the libs/frameworks/tools we use; so the idea is to use them only if their added value is weighter at the present context.
Currently, I think ES6 is enough to write simple advanced codes.

For build tools, npm appears to be  improving such a way it could be currently enough for dependency and build management over any build tool like grunt and gulp.
