### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by krazyjakee** [jsxc/jsxc#500]
After googling around I see only a couple issues here that refer to websocket support for jsxc, I'm wondering if it is supported? I notice one of the arguments against it was that the connection is reset each page view but my app (like many others) is a single page application.

I'd like to start this conversation while I investigate the code a little more to understand how I could possibly shimmy it in.

I really admire what you guys have done here.

**Comment by sualko** [comment]
In general this should be not too much work, because the underlying XMPP library supports already websockets, but in 3.x will be no native support. This is maybe something which could go into 4.x (see #463).

If you find a nice workaround, we would appreciate a [wiki entry](https://github.com/jsxc/jsxc/wiki) or also a pull request.
