### ISSUE TITLE
Programmatically join room only work on first session ( not visible in roster )

### ISSUE THREAD

**Issue by Kiwy404** [jsxc/jsxc#547]
I need to join programmatically rooms, however i have an issue with the following code :
```
var room="myroom@conference";
if(jsxc.gui.roster.getItem(room).length === 0)
   jsxc.muc.join(room, "Nickname", null, "RoomName", "", false, false);	
```
If i logon with the same user (jid) on a different browser or device (with a different XMPP resource), the room is not injected in the roster, however i can see the presence  (online) state of the room in the javascript console, as its ok except that the room is not present in the roster.

How could this issue be fixed, is it a bug ?
Greetings

**Comment by sualko** [comment]
It's probably not injected, because the room is not added to the `jsxc.xmpp.conn.muc.roomNames` list. Normally this should be handled by the muc plugin, see [lib/strophe.muc.js#L105](https://github.com/jsxc/jsxc/blob/master/lib/strophe.muc.js#L105). If you have time it would be great if you could debug this further.

**Comment by Mariick** [comment]
The rooms seems correctly added to `jsxc.xmpp.conn.muc.roomNames` list, however after multiple test with different browsers (Firefox, Edge and Chrome), it seems that programmatically join MUC at webpage startup without user action (like click on button to join muc....), even if waiting to JSXC's event `stateChange.jsxc` state 6 (READY) or `stateUIChange.jsxc` state 1, the main issue.
But if i delay the execution of they `jsxc.muc.join` lines with a setTimeout, it work everytime.

However its not a serious way, because this delay can vary depending of the client.
I find another way to solve this by adding a new event generated in the function `_processRequest` of Strophe.js library ( jsxc.dep.js (v3.2.1) at line 4809) each time a polling request is sent to the server (i noticed a correlation with the beginning of this event and the success of programmatically insert mucs at startup)  : 
```
                req.xhr.send(req.data);
                
                // If polling request (body tag without childs) generate the event
                if(req.xmlData.tagName == "body" && req.xmlData.childNodes.length == 0){
                	$(document).trigger("boshPollReq.strophe");
                }
```
And then in the app code : 
```
var firstBoshPollReq=false;  //global

$(document).on('boshPollReq.strophe',function(){
		    	if(!firstBoshPollReq){
                             // .... Programmatically MUC join at webapp startup 
                            // (need to be bookmarked because the event is a few delayed at page reload )
                             firstBoshPollReq = true;
                        }
});
```


Note : The XMPP Server is Prosody 0.9.12 (i tested also with Prosody 0.10), even if this issue seems more related to the client side.
