### ISSUE TITLE
Fix suggestion for many issues in slaves tab

### ISSUE THREAD

**Issue by Mariick** [jsxc/jsxc#550]
Instead of complicate the tab communication system, i think it can be easiest to add a `becomeMaster ` method, and when the current tab is displayed it become the master and the other master a slave (like when you close the master and one slave become the master).

In this way the issues #549 #328 ( join rooms, upload issues, chat state notifications issues in slave,...) and others can be solved.

Does anyone see any major disadvantages with this approach ?

**Comment by sualko** [comment]
Interesting idea, but I see some drawbacks/potential issues:

- How do we determine which is the active tab (master)? On demand or if the user interacts with the side? This could result in a lot of role shifts.
- To attach a previous connection, the connection has to be stopped before, otherwise the BOSH server will reject both connections. This task is critical and I am afraid that a lot of shifts will fail.

As you may noticed, we are currently refactoring/rewriting jsxc (#463) and in the current state I mocked the connection in slave tabs so that those can send xmpp stanzas via the local storage to the master. This works quite good, but now I have to test this concept in more complex situations, like audio/video calls. If this fails, I will reconsider your idea. Until then I leave this issue open. Thanks for your contribution.

**Comment by sualko** [comment]
As video calls are working just fine in the refactored version, I close this issue. Nevertheless thanks for your idea and contribution.
