### ISSUE TITLE
XMPP and nextcloud credentials are assumed to be the same

### ISSUE THREAD

**Issue by davidchisnall** [jsxc/jsxc#564]
As documented:

> JSXC assumes that you are using the same credentials for your *cloud and XMPP server.

This is less than ideal for deployments where users already have a Nextcloud account and an XMPP account.  In the pop-up box to relogin, it is possible to specify alternative credentials and then connect, but this is not cached.  Allowing the user to specify alternative credentials (as the mail plugin does, for example), would be very helpful.

**Comment by MarcelWaldvogel** [comment]
The cool thing about XMPP is that at least for situations where you control the mail, *cloud and XMPP servers, these IDs can be the same. So that is the default (see e.g. the [`xmpp-cloud-auth` installation/setup instructions](https://github.com/jsxc/xmpp-cloud-auth/wiki).

But there are options:

1. In the JSXC admin page, there is `Prefer email to user@domain` as a global setting
1. The user can individually override the XMPP address in the JSXC settings (bottom of the roster), unless the admin has forbidden that in the JSXC admin page.

I hope any of those helps.

**Comment by sualko** [comment]
Btw. Ejabberd also support stacked authentication, so users could login with there Nextcloud or Ejabberd  credentials.

Using a different password was requested before (e.g. nextcloud/jsxc.nextcloud#11), but was not implemented because 

- we currently need the password on client side and this would be a huge security risk, because every js snippet could request the password
- we don't have time to implement a server-side solution which authenticates against the xmpp server and passes the connection parameters (sid and rid) to the client-side
