### ISSUE TITLE
Login button does nothing when xmpp client enabled for some browsers.

### ISSUE THREAD

**Issue by muppeth** [jsxc/jsxc#584]
When using non-mainstream browsers (tested on midori) or latest nextcloud-dev version 20170718 pressing "Login" button in nextcloud does nothing with xmpp client enabled.

Once xmpp client is disabled, it works as expected (meaning it logs you in).

I've created an issue on nextcloud android client as this was when I first noticed the error.
https://github.com/nextcloud/android/issues/1219

**Comment by sualko** [comment]
If you ignore the issue template, I will ignore your issue :wink:. Please fill out the template and reopen this issue.

**Comment by tobiasKaminsky** [comment]
I am one of the android app devs and can confirm this behaviour.


### Expected behavior
- login via new weblogin flow should work

### Actual behavior
- weblogin flow does not work

### Steps to reproduce the behavior
1. enable xmpp
2. use android dev app
3. android dev app opens /index.php/login/flow within the app and shows a login page from the server
4. enter credentials
5. press login

### Environment
- **JSXC version:** 
- **Host system and version: nextcloud 12
- **Browser vendor and version:** android webview 
- **Any browser plugins enabled?** no
- **XMPP server vendor and version:** only enabled app, not configured 
- **Is your XMPP server working with other clients as expected?** only enabled app, not configured

### Logs
#### Javascript

nothing in android visible

#### JSXC


not related

#### XMPP

not related

#### Host

no

**Comment by sualko** [comment]
Is there a way to access `/index.php/login/flow` via browser? Because I get only `Access Forbidden
Invalid request`. Can you explain what `login/flow` is? Would it be save, if I would disable ojsxc on this page? Or could this impact the "web" version of nextcloud?

**Comment by tobiasKaminsky** [comment]
You have to access this site with header "OCS-APIREQUEST: true" or try the latest dev version of android app: https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#dev-release

It verifies the login and sends back username and app password to use in the client. It will replace the regular auth within the app.

> Would it be save, if I would disable ojsxc on this page? 

I think this would be sufficient, but if you can generate me a test version of your app, I can test it.

**Comment by muppeth** [comment]
I also noticed that sometimes when login out of nextcloud and refreshing the page, xmpp client is still visible and loged in. 
Sorry for adding perhaps unrelated information to the issue, just saw @tobiasKaminsky last post and I thought disabling the client on login page could solve that issue as well (without opening new issue).

**Comment by sualko** [comment]
It's an issue with a third-party library which requires `Object.assign`. I will try to resolve it upstream otherwise I have to include a polyfill.

@muppeth Please open an new issue with more information.

**Comment by sualko** [comment]
I found another way to handle this, but anyway I will try to fix it upstream. Hopefully today we will release a new beta version and I would be glad if you could test it.

**Comment by sualko** [comment]
Please test and verify: https://github.com/nextcloud/jsxc.nextcloud/releases/tag/v3.3.0-beta.1
