### ISSUE TITLE
remote-server-not-found while trying to send from wiuwiu.de

### ISSUE THREAD

**Issue by xpilgrim** [jsxc/jsxc#661]
### Expected behavior
sending message from wiuwiu.de account and receive it on managed my-nextcloud.de.jsxc.ch

### Actual behavior
wiuwiu.de got `remote-server-not-found`, message does not arrive on my-nextcloud.de.jsxc.ch

sendig from my-nextcloud.de.jsxc.ch to wiuwiu.de works fine

### Steps to reproduce the behavior
1. sending via gajim
2. sendig via perl xmpp

### Environment
- **JSXC version:** 3.3.2 
- **Host system and version:** Nextcloud
- **Browser vendor and version:** not used 
- **Is your XMPP server working with other clients as expected?** 
Sendig to another account e.g. blah.im is successful

**Comment by MarcelWaldvogel** [comment]
We have a certificate problem. ejabberd somehow (somewhen?) does not want to accept certificates listed with the new `certfiles:` option. Looking into it.

**Comment by xpilgrim** [comment]
Thanx for investigation and your generally work on JSXC!

**Comment by xpilgrim** [comment]
I've a cron with one xmpp message a day. It seems that the message could not received since jan 4. Perhaps this hint can help...

**Comment by MarcelWaldvogel** [comment]
Library incompatiblity problem or similar.

ejabberd-17.11 includes its own copy of (among other things) OpenSSL libraries (see processone/ejabberd#1756). After removing those libraries (renaming `/opt/ejabberd-17.11/lib/linux-x86_64` away), messages such as

> 2018-01-22 20:53:13.366 [info] <0.6261.0>@ejabberd_s2s_in:handle_auth_failure:206 (tls|<0.6260.0>) Failed inbound s2s EXTERNAL authentication wiuwiu.de -> sample-host.jsxc.ch (2A01:4F8:190:30E1::2): unable to get local issuer certificate

disappeared. Maybe this was related to the fact that the bundled libraries referred to `/tmp/local/ssl/certs` and `/tmp/local/ssl/cert.pem` instead of the appropriate paths in `/etc/ssl/certs`. Obviously, there were no CA root certificates there…

(`strace`, you saved my life. Again. Thanks to one of the admin's best bug-finding tools!)
