### ISSUE TITLE
Managed registration failed

### ISSUE THREAD

**Issue by crewhudson** [jsxc/jsxc#668]
I must apologize I am very new to this. 
Please let me know if you need any further information. Most likely this is all on my end
### Expected behavior
Tried to Register using your managed  service

### Actual behavior
Registration failed

Sorry we couldn't complete your registration.

Your Nextcloud server cannot be used because HTTPSConnectionPool(host='------------.net', port=443): Read timed out. (read timeout=5)

Please report this to our issue tracker and mention the request id G4BlJfw7m3q7US30wjHa

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** latest 
- **Host system and version:**  13.0.0
- **Browser vendor and version:** Chrome
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by crewhudson** [comment]
Just to update, I have checked and my port 443 is open. I even checked with ssllabs.com

**Comment by crewhudson** [comment]
Another update
I am now able to register but when I try to login into the chat like it asks it says Im not able to log in and maybe my password is wrong?
I have tried to reset and try it again but still not working.
I know I am doing something wrong.... Any help is greatly appreciated.
By the way, this app is fantastic and I have been enjoying using it with my family.
Really convenient!

**Comment by MarcelWaldvogel** [comment]
Sorry for the delay!

## Analysis

We have connection timeouts and request timeouts set to 5 seconds each, in order to reduce the impact of Nextcloud server problems onto our system. (And to have the [fallback user cache](https://github.com/jsxc/xmpp-cloud-auth/blob/master/doc/Cache.md) kick in as fast as possible.)

This was the reason for the first 10 registration timeouts. The 3 successful registration requests took 6, 9, and 9 seconds (connect+read) each (the log file only shows cumulative delay), barely below the 5+5 seconds maximum.

After the registration, I see what looks like strange read timeouts (`('Connection aborted.', BadStatusLine("''",))`)and connection timeouts where the password apparently does not match (`UNREACHABLE: Cache says password for t**@******** is False`)

Right now, my manual tests against your server take about 2-3 seconds. Your server seems to be rather slow.

## Resolution

I have increased the read timeout from 5 to 10 seconds. So several of the timeouts should go away.

The goal of the connection timeout is to detect unreachable Nextcloud instances when connecting with other clients than JSXC. Then, it is good to fall back to the cache; therefore, I do not want to globally increase the connection timeout globally for now.

Please let me know if your problems go away.

**Comment by sualko** [comment]
Due to inactivity I close this issue.

**Comment by crewhudson** [comment]
Hello, 

I sincerely apologize for my late reply. I just wanted to say, thank for you assistance. Your explanation was very helpful. Everything is working fine now.
Thank you for all of your hard work!
