### ISSUE TITLE
Managed (Beta service) down

### ISSUE THREAD

**Issue by koarlmichael** [jsxc/jsxc#689]
The service is unfortunately not available:
xmpp.jsxc.ch

**Comment by MarcelWaldvogel** [comment]
Noticed it myself, but was away from a computer. Will look into it right now.

Sorry for the inconvenience!

**Comment by MarcelWaldvogel** [comment]
I am sorry, our provider's infrastructure is down.

I will try to reach them, but due to the Easter holidays, they will probably be unable to look into that before tomorrow morning.

BTW: We are in the process of changing our hosting infrastructure. So we hope this will not take as long to fix next time there is a problem.

**Comment by MarcelWaldvogel** [comment]
Service is reachable again. Apparently, only the network connection was down. The machine claims to have 88 days of uninterrupted uptime.

**Comment by MarcelWaldvogel** [comment]
The machine was disconnected between 08:42 and 15:28 UTC today. Sorry for the inconvenience!

**Comment by koarlmichael** [comment]
Many Thanks. Is a great service what you offer here 👍

**Comment by MarcelWaldvogel** [comment]
Update: I have just learned that it was the upstream ISP who had the problem with a router linecard that broke.
