### ISSUE TITLE
Can not receive message if more than 1000 concurrent users

### ISSUE THREAD

**Issue by johnsonjruban** [jsxc/jsxc#725]
We are using ejabberd XMPP server with JSXC client in our PHP website, If more than 1000 concurrent users chatting. There is a time delay or sometimes can not receive message properly. Is that ok ejabberd and JSXC combination or any settings/way of calling functions need to change?

**Comment by MarcelWaldvogel** [comment]
We're glad to hear that you are using JSXC with so many concurrent users! (And sorry to hear about the slowness.)

The way you describe it, it seems like you are not using one of our "standard" installations (e.g. Nextcloud, Ilias, …)? But I doubt this is the source of the lag, timeouts, and resulting missing messages.

I would expect that *ejabberd* is overloaded handling the BOSH requests. Can you look at the number of BOSH requests per minute in the ejabberd log? What is the CPU usage, load average, memory usage for the *ejabberd* server host?

Without knowing more about the problem, I see two short-term options and one long-term option:

1. Tune *ejabberd* to handle more requests per second
   1. Increase CPU/memory available to *ejabberd*
   1. Make sure the requests do go through as few intermediaries on that machine as possible (i.e., not have an Apache proxy on the same machine as well)
   1. Improve the TLS configuration or offload TLS processing to another machine
1. Reduce the number of BOSH requests per second
   1. Increase the [`max_inactivity`](https://docs.ejabberd.im/admin/configuration/#options-1) setting in `ejabberd.yml` from 30 to e.g. 60 seconds.
1. (Long-term) Change JSXC to use Websockets (instead of BOSH)

Can you tell me more about your setup? What options do you think you might use? Where do you need additional help?

**Comment by sualko** [comment]
Any update on this?

**Comment by sualko** [comment]
I close this issue due to inactivity. Please reopen if needed.
