### ISSUE TITLE
Mam will not work with omemo.

### ISSUE THREAD

**Issue by goors** [jsxc/jsxc#744]
https://github.com/jsxc/jsxc/blob/29b39bfdbbf0c27c7c39f8c8edf552f3ee0dba48/src/plugins/omemo/lib/Omemo.ts#L146

If you delete localstorage, you will generate new device id and because of that condition mam decrypt will not work. I mean I understand that if you have just only one device and you are sure that you will not have any other devices. That being said Messages across devices will not work. Meaning jsxc omemo will work only if you have once device. Only device that has received messages will be able to decrypt it. Correct me if I am wrong please.

**Comment by sualko** [comment]
> If you delete localstorage, you will generate new device id and because of that condition mam decrypt will not work.

That's right, because you also deleted your private key. There is nothing we can do in this case.

>  That being said Messages across devices will not work. Meaning jsxc omemo will work only if you have once device. 

This is not right. We encrypt a message for all of our devices and those of our recipient. See https://github.com/jsxc/jsxc/blob/29b39bfdbbf0c27c7c39f8c8edf552f3ee0dba48/src/plugins/omemo/lib/Peer.ts#L46

> Correct me if I am wrong please.

I guess you have a wrong understanding of OMEMO. OMEMO is device based and not identity based. There is not one key per user, there is only one key per device.

If you have further questions, please write another comment.
