### ISSUE TITLE
Fetch User list from server

### ISSUE THREAD

**Issue by mitulverma13** [jsxc/jsxc#772]
While adding a new user I am able to input any name which is not available in the server. I want to display User List from the server and I should be able to add only those users.

**Comment by MarcelWaldvogel** [comment]
First of all, there is an issue template, which helps us avoid some questions. It would be great if you could fill this in, at least the relevant parts.

First of all: Which backend are you using?

[XMPP](https://en.wikipedia.org/wiki/XMPP), the instant messaging standard used by JSXC, allows for a global network of interoperable, federated servers. So, being able to add users which are not on your server is in there by design.

And depending on the backend you use, there are options to automatically add users to your roster, e.g. all the members of the group you are in.

**Comment by mitulverma13** [comment]
I am using ejabberd, I want to give users the option to add desirable users, not all users as the list of users is too long. There is the same feature when we Join Rooms it gives a list of all available Rooms from the server. I need the same functionality while adding Users

**Comment by MarcelWaldvogel** [comment]
[`xmpp-cloud-auth`](https://github.com/jsxc/xmpp-cloud-auth) gives you the option to have automatic Shared Rosters based on the Nextcloud groups. Or you can add Shared Rosters manually to XMPP.

I do not think *ejabberd* has an option to list all the users.

**Comment by sualko** [comment]
You can get the same functionality with the `getUsers` option: https://github.com/jsxc/jsxc/blob/88c3a70e763b5b132685444eab3656d1afa9ce79/src/jsxc.lib.options.js#L219-L227
