### ISSUE TITLE
OMEMO-encrypted file transfer (http_upload) possible?

### ISSUE THREAD

**Issue by mw80** [jsxc/jsxc#832]
### Expected behavior
OMEMO-encrypted file transfer via http_upload possible

### Actual behavior
Shown "aesgcm://server.com:5281/upload/-xdR5Zega2FdpN-y/Snap11.jpg#dcad6f2f345b69feab6f1d4e68e030c505816bfe2d59f272a78b6ee186301d9a71a0f7404f54aad5f251a201674081c8"

### Steps to reproduce the behavior
1. Send OMEMO-encrypted file via http_upload
2.
3.

### Environment
- **JSXC version:** 
4.0.0
- **Host system and version:** 
Nextcloud
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

**Comment by sualko** [comment]
We are aware of this issue, but the XSF had some reservations against https://xmpp.org/extensions/inbox/omemo-media-sharing.html and therefore I think it's not a good practice to implement something "unofficial". A second issue is that we would could not decrypt the file on the fly, because this would harm the users privacy.

**Comment by mw80** [comment]
Ok, thanks for clarification.
