### ISSUE TITLE
File Transer does not work in chat

### ISSUE THREAD

**Issue by zawthanoo** [jsxc/jsxc#953]
I am testing a chat application using jsxc + openfire. I get some error which is I cannot transfer the file in chat.

![image](https://user-images.githubusercontent.com/6555298/100834878-0ac21980-349b-11eb-90f6-b3ef5a22925a.png)

![image](https://user-images.githubusercontent.com/6555298/100834928-262d2480-349b-11eb-98e2-52e51997d934.png)

![image](https://user-images.githubusercontent.com/6555298/100835059-5f659480-349b-11eb-9399-95918a81f569.png)

Is there any config for file-transfer port?

Console Log is

![image](https://user-images.githubusercontent.com/6555298/100837934-eae12480-349f-11eb-9f23-788f13696af7.png)

**Comment by zawthanoo** [comment]
I solve this issue.  we need to install "Http File Upload " plugin in openfire.

![image](https://user-images.githubusercontent.com/6555298/101142322-d76ebe80-3643-11eb-9655-10f9260978c1.png)

But, it is work on Chrome. Firefox get the following issue. It is another issue.

![image](https://user-images.githubusercontent.com/6555298/101142517-19980000-3644-11eb-909b-e5359bbbbc19.png)

![image](https://user-images.githubusercontent.com/6555298/101142586-33394780-3644-11eb-8f59-383b5009e85a.png)

**Comment by sualko** [comment]
Hi, thanks for testing this application. The error is indicating that your csp or cors settings are not correct. This is not related to jsxc and can't be fixed by us. Please try to set your headers appropriate and try again. There are plenty of similar questions in the web. So you should find a answer like https://discourse.igniterealtime.org/t/not-allowed-by-access-control-allow-origin/56155/3
